// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetConnections() {
  return window['go']['main']['App']['GetConnections']();
}

export function GetUserPermissions(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetUserPermissions'](arg1, arg2, arg3);
}

export function RegisterDatabase(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['RegisterDatabase'](arg1, arg2, arg3, arg4, arg5);
}
